// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgObckCPDi7gW8GGJeKel1VOT4UI_nC1A',
    appId: '1:165153876385:web:c8fa824f2a6cabd77bc3e0',
    messagingSenderId: '165153876385',
    projectId: 'cancer-detector-e8db8',
    authDomain: 'cancer-detector-e8db8.firebaseapp.com',
    storageBucket: 'cancer-detector-e8db8.appspot.com',
    measurementId: 'G-PRMV5C5HT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsilO4TuZjqUAG7d_dybPt13yMCcPGJbM',
    appId: '1:165153876385:android:545473425118ceb87bc3e0',
    messagingSenderId: '165153876385',
    projectId: 'cancer-detector-e8db8',
    storageBucket: 'cancer-detector-e8db8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCILtvL9XB27-NWBNGfLCMgSHygnZzqgPc',
    appId: '1:165153876385:ios:cd34967a84a60ea07bc3e0',
    messagingSenderId: '165153876385',
    projectId: 'cancer-detector-e8db8',
    storageBucket: 'cancer-detector-e8db8.appspot.com',
    iosClientId: '165153876385-q1l3s53pj2kkpkicd7nrr42jvhnjevmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancerDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCILtvL9XB27-NWBNGfLCMgSHygnZzqgPc',
    appId: '1:165153876385:ios:cd34967a84a60ea07bc3e0',
    messagingSenderId: '165153876385',
    projectId: 'cancer-detector-e8db8',
    storageBucket: 'cancer-detector-e8db8.appspot.com',
    iosClientId: '165153876385-q1l3s53pj2kkpkicd7nrr42jvhnjevmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancerDetector',
  );
}
